### PR TITLE
Add intent id to webform results

### PR DESCRIPTION
**Pull request by katzmo**

### CODE REVIEW

**Review by torotil — CHANGES_REQUESTED** [review]
Could you add tests for these two methods?

**Comment by katzmo** [comment]
> Could you add tests for these two methods?

What should the tests test? Just calling the methods does not test anything useful? But how would I get the output of webform results here? :thinking:

**Comment by torotil** [comment]
> What should the tests test? Just calling the methods does not test anything useful? But how would I get the output of webform results here?

I would suggest exactly that. You could also call `webform_paymethod_select_implements_data_interface()` on the controller. And if you want to be even more thorough you could call `webform_paymethod_select_webform_results_download_submission_information_data()` as well. Should be easy enough to mock.

**Comment by katzmo** [comment]
The module and tests don’t have a dependency on `webform_paymethod_select` yet, it doesn’t seem worth it to add it and mock a node and a submission just to test 1 line of code!?

**Comment by torotil** [comment]
> The module and tests don’t have a dependency on `webform_paymethod_select`

It does. webform_paymethod_select is enabled in the travis.yml (see https://github.com/moreonion/stripe_payment/blob/7.x-2.x/.travis.yml#L37)

> it doesn’t seem worth it to add it and mock a node and a submission just to test 1 line of code!?

I’m fine with just testing the two methods and that they pass the interface check. You were suggesting that this wasn’t thorough enough for you. ;-)

**Review by torotil — APPROVED** [review]

**Pull request merged**
